<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    public function run()
    {
        $clients = [
            'ZEINA ISABEL MARTÍNEZ DE VALLE',
            'MARCELA YANETH QUINTANILLA PINEDA',
            'LITZI YANUCELI RAMOS ZAVALA',
            'SAUL ROBERTO NÚÑEZ MORALES',
            'RICARDO ESTEBAN MARTÍNEZ RIVAS',
            'KEYLYN YAJAIRA RIVAS LÓPEZ',
            'PEDRO ALEXANDER VALLE',
            'MARTIR ANTONIO SORTO',
            'NOE ALEJANDRO ÁNGEL ALVARENGA',
            'OSCAR ALEXANDER ORTIZ CAÑAS',
            'FRANCISCO MÉNDEZ ACOSTA',
            'MARÍA LUZ RIVERA',
            'YANETH MARLENE ALVEÑO DE VARELA',
            'ARMIDIO FLORES AVILES',
            'TORIBIO ORELLANA',
            'MARÍA MAGDALENA RODRÍGUEZ DE RODRÍGUEZ',
            'ERNESTINA HERNÁNDEZ',
            'JOSÉ FÉLIX MEDINA CRUZ',
            'JOSÉ JAIME MORAN ESCOBAR',
            'JOSÉ RAMON TRIGUEROS FLORES',
            'YAMILETH DE LOS ÁNGELES MORAN ESCOBAR',
            'MARÍA EDUVIGES RODAS VELÁSQUEZ',
            'MARTA ALICIA RAMÍREZ DE PEÑA',
            'ESTEFANY MICHELL SIBRIAN ESPINOZA',
            'REINA DEL CARMEN CRUZ RIVAS',
            'LESLY ALEJANDRA PÉREZ MEMBREÑO',
            'SAUL ERNESTO ROSALES LÓPEZ',
            'MARIO ERNESTO AYALA LÓPEZ',
            'ALVARO REYNALDO RIVERA AVELAR',
            'DORALICIA BRIZUELA DE OCHOA',
            'WANDY ESTERLI CRUZ VARELA',
            'ISABEL MORENO DE MEJIA',
            'EVELYN MARISOL REYES RODRÍGUEZ',
            'MANUEL DE JESÚS VALDIZÓN BARILLAS',
            'NESTOR ERICK PORTILLO SALAZAR',
            'MIRNA YAMILETH BATREZ PÉREZ',
            'LUIS ALFREDO GUILLEN PORTILLO',
            'MARTIN ASCENCIO',
            'DORA MARINA ROGEL RIVAS',
            'GUILLERMO EDGARDO PEÑA AVELAR (2)',
            'KENIA BEATRIZ MEJÍA AVELAR (2)',
            'MARÍA MARGOTH TRUJILLO',
            'INÉS YESENIA HERNÁNDEZ DE RODRÍGUEZ',
            'LOYDA ELIZABETH CHICAS BARILLAS',
            'INGRY YAMILETH LUNA CALDERÓN',
            'MARÍA ISABEL GÁMEZ POLANCO',
            'JOSUÉ FERNANDO RAMÍREZ SARAVIA',
            'REY ALEJANDRO GONZALES CARTAGENA',
            'HÉCTOR ANTONIO MARTÍNEZ UMAÑAA',
            'SANDY XIOMARA GUTIÉRREZ ALFARO',
            'LEONEL EBERARDO ORTIZ HERNÁNDEZ',
            'YOALMO DANIEL HERNÁNDEZ',
            'LUIS ALFREDO GUILLEN PORTILLO (2)',
            'SALVADOR VALLE TORRES',
            'MOISES ALEXANDER AGUILAR MARTÍNEZ',
            'JOSÉ EMILIO ARDÓN GARCÍA',
            'MARGARITA DEL CARMEN CORTEZ AYALA',
            'YANETH MARLENE ALVEÑO DE VARELA (2)',
            'ORCI VLADIMIR REYES ORELLANA',
            'CARLOS CACERES AGUILAR',
            'NUBIA ELIZABETH HERNÁNDEZ DE BARILLAS',
            'BERTA ALICIA AGUILAR DE ESPINOZA',
            'GEOVANY ÁLVAREZ',
            'EDUARDO GONZÁLEZ HUEZO',
            'ROSALINA SANTAMARÍA',
            'KENIA BEATRIZ MEJÍA AVELAR',
            'ÁNGEL ANTONIO MONTALVO LÓPEZ CISNEROS',
            'YESENIA REYES',
            'JOSÉ FRANCISCO ORELLANA',
            'JOSÉ SANTIAGO HERNÁNDEZ VALLE',
            'GUILLERMO EDGARDO PEÑA AVELAR',
            'MARINA ESTER RODRÍGUEZ DE OSEJO',
            'LUCILA CISNEROS DE HERNÁNDEZ',
            'GLADIS DE JESÚS MEJÍA',
            'CAROLINA DEL CARMEN GALDÁMEZ DURAN',
            'JUAN JOSÉ CASTILLO RAMÍREZ',
            'GONZALO ARNULFO RAMÍREZ',
            'NIDIA ARGENTINA CHILIN BARILLAS',
            'ELVA MARGARITA MIRANDA MORALES',
            'HÉCTOR ABILIO MENDOZA',
            'MARÍA ELENA HERNÁNDEZ VDA DE CANTARERO',
            'CARLOS ANTONIO MORAN AGUILAR',
            'DAVID ALFREDO ORELLANA CALDERÓN',
            'SANTOS AMERICO HERNÁNDEZ FLORES',
            'ELVIRA DEL CARMEN GÁMEZ',
            'BLANCA ESTELA ARDÓN MANCÍA',
            'MIRNA GRICELDA RODRÍGUEZ CHILIN',
            'FELIPE MEJÍA ORELLANA',
            'JOSÉ LUIS SOSA CASTILLO',
        ];

        $counter = 1;
        foreach ($clients as $name) {
            Client::create([
                'name' => $name,
                'phone' => '2222-' . str_pad($counter, 4, '0', STR_PAD_LEFT),
                'address' => 'San Pablo Tacachico',
                'service' => 'No especificado',
                'document_type' => 'dui',
                'document_number' => '00000000-' . ($counter % 10),
                'email' => strtolower(str_replace(' ', '', $name)) . '@ejemplo.com',
                'latitude' => null,
                'longitude' => null,
                'nro_luz' => (string) (10000 + $counter),
                'installation_address' => 'San Pablo Tacachico',
                'notes' => 'Cliente migrado – verificar datos reales',
            ]);
            $counter++;
        }
    }
}